### ISSUE TITLE
Typo in customizing-the-backend documentation

### ISSUE THREAD

**Issue by abumalick** [solidusio/edgeguides#122]
There is a typo in customizing the backend documentation:
> how to set it upeckout/address) to accomplish tha

https://github.com/solidusio/edgeguides/blame/a6e649fe001028c7c4bb00d08c3f5f76c99b3cbc/docs/customization/customizing-the-backend.mdx#L106

I don't know what should be written there.

**Comment by waiting-for-dev** [comment]
Thanks for reporting. That was just some trick by VIM :slightly_smiling_face: Fixed in #123

**Comment by abumalick** [comment]
You are welcome. Thank you for maintaining this 👍🏻
